# Generated by Django 4.2.4 on 2023-08-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modems', '0006_delete_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('timestamp', models.FloatField()),
                ('modem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modem', to='modems.modem')),
            ],
        ),
    ]
