# Generated by Django 4.2.4 on 2023-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('USB', 'USB'), ('Android', 'Android'), ('iPhone', 'iPhone')], max_length=10)),
                ('public_ip', models.GenericIPAddressField()),
                ('ipv4', models.GenericIPAddressField()),
                ('ipv6', models.GenericIPAddressField()),
            ],
        ),
    ]
