# Generated by Django 4.2.4 on 2023-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0002_modem_carrier_alter_modem_ipv4_alter_modem_ipv6'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_mode_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
