# Generated by Django 4.2.4 on 2023-08-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0003_featuresettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='modem',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('timestamp', models.FloatField()),
                ('modem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modems.modem')),
            ],
        ),
    ]
