# Generated by Django 4.2.4 on 2023-08-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0004_modem_phone_number_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='modem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modem', to='modems.modem'),
        ),
    ]
