# Generated by Django 4.2.4 on 2023-08-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0005_alter_sms_modem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
    ]
