# Generated by Django 4.2.4 on 2023-08-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modems', '0006_delete_sms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modem',
            options={'ordering': ['id']},
        ),
    ]
